import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import { useMutation, useQuery } from '@apollo/client';
import {
  ADD_TASK,
  EDIT_TASK,
  DELETE_TASK,
  GET_TASKS,
} from '../graphql/queries';

const Home: NextPage = () => {
  const [enteredTask, setEnteredTask] = useState('');

  const { data, error, loading } = useQuery(GET_TASKS);

  const changeInputHandler = (event: React.FormEvent<HTMLInputElement>) => {
    const taskMessage = event.currentTarget.value.trim();
    setEnteredTask(taskMessage);
  };

  const submitHandler = (event: React.FormEvent) => {
    event.preventDefault();
    console.log('SEND');
  };

  // useEffect(() => {
  //   // console.log(loading);
  //   // console.log(error);
  //   console.log(data);
  // }, [data]);

  return (
    <div className='max-w-xl mx-auto w-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header className='bg-blue-600 pb-8 pt-4 rounded-bl-[2.5rem]'>
        <h1 className='text-center text-3xl mb-8 text-white'>
          Fullstack ToDo App
        </h1>
        <form className='flex flex-col items-center' onSubmit={submitHandler}>
          <input
            type='text'
            className='border rounded-3xl px-6 py-2 text-lg'
            placeholder='Add task to do...'
            onChange={changeInputHandler}
          />
          {/* <button type='submit' className='bg-white rounded-3xl px-6 py-2 mt-10'>Submit</button> */}
        </form>
      </header>
      <main className='mt-6 mx-2 md:mx-0'>
        {loading && <h2 className='text-center text-3xl'>Loading...</h2>}
        {!loading && (
          <ul className='flex flex-col items-start'>
            {data.tasks.map((task: { id: string; task: string }) => (
              <li className='text-lg sm:text-xl flex justify-between w-full my-1 items-center' key={task.id}>
                {task.task}
                <div>
                  <button type='button' className='border bg-blue-600 py-1 px-2 rounded-xl text-white cursor-pointer'>edit</button>
                  <button type='button' className='border bg-blue-600 py-1 px-2 rounded-xl text-white cursor-pointer'>delete</button>
                </div>
              </li>
            ))}
          </ul>
        )}
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
